version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

  fluentd:
    build: ../logging/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.3.2
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: kibana:7.3.2
    ports:
      - "8080:5601"

networks:
  back_net:
  front_net:

