version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    container_name: mongodb-service
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    container_name: ui-service
    image: ${USER_NAME}/ui:${IMAGE_VERSION}
    ports:
      - ${PORT}:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    container_name: post-service
    image: ${USER_NAME}/post:${IMAGE_VERSION}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    container_name: comment-service
    image: ${USER_NAME}/comment:${IMAGE_VERSION}
    networks:
      back_net:
        aliases:
        - comment
      front_net:
        aliases:
        - comment

volumes:
  post_db:

networks:
  back_net:
  front_net:

