services:
  post_db:
    image: mongo:${MONGO_VERSION}
  ui:
    image: ${USERNAME}/ui:${BUILD_VERSION}
      - ${PORT}:9292/tcp
    command: puma --debug -w 2
  post:
    image: ${USERNAME}/post:${POST_VERSION}
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}

